/* Gestión de Precios y Promociones — Tu Esquina
   Módulo independiente, sin frameworks. Conserva las claves laEsquina.* existentes. */
const COMMERCIAL_KEYS = {
  promotions: 'laEsquina.promotions', combos: 'laEsquina.combos',
  priceHistory: 'laEsquina.priceHistory', commercial: 'laEsquina.commercialSettings',
  migration: 'laEsquina.commercialMigration.v1'
};
const COMMERCIAL_DEFAULTS = {
  generalMarkup: 30, minimumMargin: 20, targetMargin: 30, rounding: '50',
  discountLimit: 15, defaultPriority: 10, allowStacking: false, maxBulkWithoutAuth: 20,
  expirationSuggestionDays: 15, inactivityDays: 30, highStockMultiplier: 3,
  category: {}, brand: {}, product: {}
};
function loadCommercialArray(key) { try { const value = JSON.parse(localStorage.getItem(key)); return Array.isArray(value) ? value : []; } catch { return []; } }
function cargarPromociones() { return loadCommercialArray(COMMERCIAL_KEYS.promotions); }
function guardarPromociones(value = promotions) { localStorage.setItem(COMMERCIAL_KEYS.promotions, JSON.stringify(value)); }
function cargarCombos() { return loadCommercialArray(COMMERCIAL_KEYS.combos); }
function guardarCombos(value = combos) { localStorage.setItem(COMMERCIAL_KEYS.combos, JSON.stringify(value)); }
function cargarHistorialPrecios() { return loadCommercialArray(COMMERCIAL_KEYS.priceHistory); }
function guardarHistorialPrecios(value = priceHistory) { localStorage.setItem(COMMERCIAL_KEYS.priceHistory, JSON.stringify(value)); }
function cargarConfiguracionComercial() { try { return { ...COMMERCIAL_DEFAULTS, ...(JSON.parse(localStorage.getItem(COMMERCIAL_KEYS.commercial)) || {}) }; } catch { return structuredClone(COMMERCIAL_DEFAULTS); } }
function guardarConfiguracionComercial(value = commercialSettings) { localStorage.setItem(COMMERCIAL_KEYS.commercial, JSON.stringify(value)); }

let promotions = cargarPromociones(), combos = cargarCombos(), priceHistory = cargarHistorialPrecios();
let commercialSettings = cargarConfiguracionComercial(), pricingTab = 'summary', commercialAction = null, bulkPricePreview = [];
const finiteNonNegative = value => { const parsed = Number(value); return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0; };
function calcularGananciaUnidad(precioVenta, costoPromedio) { return finiteNonNegative(precioVenta) - finiteNonNegative(costoPromedio); }
function calcularRecargoSobreCosto(precioVenta, costoPromedio) { const cost = finiteNonNegative(costoPromedio); return cost > 0 ? calcularGananciaUnidad(precioVenta, cost) / cost * 100 : 0; }
function calcularMargenSobreVenta(precioVenta, costoPromedio) { const price = finiteNonNegative(precioVenta); return price > 0 ? (price - finiteNonNegative(costoPromedio)) / price * 100 : 0; }
function calcularPrecioSugerido(costoPromedio, porcentaje, tipo = 'recargo') { const cost = finiteNonNegative(costoPromedio), pct = finiteNonNegative(porcentaje); if (tipo === 'margen') return pct >= 100 ? 0 : cost / (1 - pct / 100); return cost * (1 + pct / 100); }
function calcularPrecioMinimo(costoPromedio, recargoMinimo = commercialSettings.generalMarkup) { return calcularPrecioSugerido(costoPromedio, finiteNonNegative(recargoMinimo), 'recargo'); }
function redondearPrecioComercial(value, mode = 'none') { const price = finiteNonNegative(value); if (!price || mode === 'none') return Math.round(price * 100) / 100; const up = String(mode).startsWith('up-'); const multiple = Number(String(mode).replace('up-', '')) || 1; return (up ? Math.ceil(price / multiple) : Math.round(price / multiple)) * multiple; }
function configuracionParaProducto(product) { return { ...commercialSettings, ...(commercialSettings.brand?.[product.brand] || {}), ...(commercialSettings.category?.[product.category] || {}), ...(commercialSettings.product?.[product.id] || {}) }; }
function evaluarRentabilidadProducto(product, price = product.precioVenta) { const config = configuracionParaProducto(product), cost = finiteNonNegative(product.costoPromedio), current = finiteNonNegative(price), margin = calcularMargenSobreVenta(current, cost); if (!current) return { key: 'no-price', label: 'Sin precio', tone: 'neutral' }; if (!cost) return { key: 'no-cost', label: 'Sin costo', tone: 'neutral' }; if (current < cost) return { key: 'loss', label: 'Venta con pérdida', tone: 'danger' }; if (product.requiereRevisionPrecio) return { key: 'review', label: 'Pendiente de revisión', tone: 'info' }; if (margin < config.minimumMargin) return { key: 'low-margin', label: 'Margen bajo', tone: 'warning' }; return { key: 'profitable', label: 'Rentable', tone: 'success' }; }

function migrateCommercialProducts() {
  let changed = false;
  products.forEach(p => {
    const defaults = configuracionParaProducto(p), before = JSON.stringify(p);
    Object.assign(p, {
      id: p.id || uid(), nombre: p.nombre ?? p.name ?? 'Producto sin nombre', marca: p.marca ?? p.brand ?? 'Sin marca',
      categoria: p.categoria ?? p.category ?? 'General', contenido: finiteNonNegative(p.contenido ?? p.content ?? 1) || 1,
      unidadMedida: p.unidadMedida ?? p.unit ?? 'Unidad', codigoBarras: p.codigoBarras ?? p.code ?? '',
      stock: finiteNonNegative(p.stock), stockMinimo: finiteNonNegative(p.stockMinimo ?? p.minStock),
      ultimoCostoCompra: finiteNonNegative(p.ultimoCostoCompra), costoPromedio: finiteNonNegative(p.costoPromedio),
      precioVenta: finiteNonNegative(p.precioVenta ?? p.price), porcentajeRecargoPredeterminado: finiteNonNegative(p.porcentajeRecargoPredeterminado ?? p.porcentajeRentabilidadPredeterminado ?? defaults.generalMarkup),
      porcentajeMargenObjetivo: finiteNonNegative(p.porcentajeMargenObjetivo ?? defaults.targetMargin),
      tipoCalculoPredeterminado: p.tipoCalculoPredeterminado ?? p.tipoRentabilidadPredeterminado ?? 'recargo',
      tipoRedondeoPredeterminado: p.tipoRedondeoPredeterminado ?? defaults.rounding,
      fechaUltimoCambioPrecio: p.fechaUltimoCambioPrecio ?? p.fechaModificacion ?? '', fechaUltimaCompra: p.fechaUltimaCompra ?? '',
      requiereRevisionPrecio: Boolean(p.requiereRevisionPrecio), activo: p.activo !== false
    });
    p.precioMinimo = finiteNonNegative(p.precioMinimo) || calcularPrecioMinimo(p.costoPromedio, defaults.minimumMargin);
    p.price = p.precioVenta; p.name = p.nombre; p.brand = p.marca; p.category = p.categoria;
    if (JSON.stringify(p) !== before) changed = true;
  });
  if (changed) save();
  localStorage.setItem(COMMERCIAL_KEYS.migration, '1');
}
function persistCommercial() { guardarPromociones(); guardarCombos(); guardarHistorialPrecios(); guardarConfiguracionComercial(); save(); }
function recordPriceChange(product, oldPrice, newPrice, reason, origin = 'edición manual', extra = {}) {
  const now = new Date(), difference = newPrice - oldPrice;
  priceHistory.unshift({ id: uid(), fecha: now.toISOString().slice(0,10), hora: now.toTimeString().slice(0,8), productoId: product.id,
    nombreProducto: product.name, marca: product.brand, categoria: product.category, presentacion: presentation(product), costoPromedio: product.costoPromedio,
    precioAnterior: oldPrice, precioNuevo: newPrice, diferenciaPesos: difference, diferenciaPorcentaje: oldPrice ? difference / oldPrice * 100 : 0,
    recargoAnterior: calcularRecargoSobreCosto(oldPrice, product.costoPromedio), recargoNuevo: calcularRecargoSobreCosto(newPrice, product.costoPromedio),
    margenAnterior: calcularMargenSobreVenta(oldPrice, product.costoPromedio), margenNuevo: calcularMargenSobreVenta(newPrice, product.costoPromedio),
    motivo: reason, origen: origin, usuario: business?.user || 'Administrador', ...extra });
}
function updateProductPrice(product, next, reason, origin) { const value = finiteNonNegative(next); if (!value) return false; const old = product.precioVenta; if (old !== value) recordPriceChange(product, old, value, reason, origin); product.price = product.precioVenta = value; product.fechaUltimoCambioPrecio = new Date().toISOString(); product.requiereRevisionPrecio = false; return true; }
function authorizeSensitive(reason) { if (estaConfiguracionAutorizada()) return true; const password = prompt(`${reason}\nIngresá la clave de Configuración:`); if (!validarClaveConfiguracion(password)) { showToast('Operación cancelada: clave incorrecta', 'error'); return false; } sessionStorage.setItem(CONFIG_AUTH_KEY, 'true'); return true; }

function promotionState(p, at = new Date()) { if (p.estado === 'borrador' || p.estado === 'pausada' || p.estado === 'finalizada') return p.estado; const start = p.fechaInicio ? localDate(p.fechaInicio) : null, end = p.fechaFin ? localDate(p.fechaFin) : null; if (end) end.setHours(23,59,59,999); if (end && at > end) return 'vencida'; if (start && at < start) return 'programada'; return p.activa !== false ? 'activa' : 'pausada'; }
function promotionMatches(promo, product, date, method) {
  if (promotionState(promo, date) !== 'activa') return false;
  if (promo.productoIds?.length && !promo.productoIds.includes(product.id)) return false;
  if (promo.marcaIds?.length && !promo.marcaIds.includes(product.brand)) return false;
  if (promo.categoriaIds?.length && !promo.categoriaIds.includes(product.category)) return false;
  if (promo.metodoPagoIds?.length && !promo.metodoPagoIds.includes(method)) return false;
  if (promo.diasSemana?.length && !promo.diasSemana.map(Number).includes(date.getDay())) return false;
  const time = date.toTimeString().slice(0,5); if (promo.horaInicio && time < promo.horaInicio || promo.horaFin && time > promo.horaFin) return false;
  return promo.limiteUnidades == null || finiteNonNegative(promo.unidadesAplicadas) < finiteNonNegative(promo.limiteUnidades);
}
function calculatePromotionLine(promo, product, quantity) {
  const normal = product.precioVenta * quantity, price = product.precioVenta; let total = normal;
  switch (promo.tipo) {
    case 'porcentaje': case 'categoria': case 'marca': case 'metodo_pago': total = normal * (1 - Math.min(100, finiteNonNegative(promo.porcentaje)) / 100); break;
    case 'fijo': total = Math.max(0, normal - finiteNonNegative(promo.descuentoFijo) * quantity); break;
    case 'precio_fijo': total = finiteNonNegative(promo.precioPromocional) * quantity; break;
    case 'cantidad': { const required = Math.max(1, finiteNonNegative(promo.cantidadRequerida)); total = Math.floor(quantity / required) * finiteNonNegative(promo.precioPromocional) + quantity % required * price; break; }
    case 'dos_por_uno': total = (Math.floor(quantity / 2) + quantity % 2) * price; break;
    case 'tres_por_dos': total = (Math.floor(quantity / 3) * 2 + quantity % 3) * price; break;
    case 'segunda_descuento': total = normal - Math.floor(quantity / 2) * price * Math.min(100, finiteNonNegative(promo.porcentaje || 50)) / 100; break;
    case 'desde_cantidad': total = quantity >= finiteNonNegative(promo.cantidadRequerida) ? normal * (1 - Math.min(100, finiteNonNegative(promo.porcentaje)) / 100) : normal; break;
  }
  return { normal, total: Math.max(0, total), discount: Math.max(0, normal - total), unit: quantity ? total / quantity : price };
}
function obtenerPromocionesAplicables(producto, carrito = cart, fecha = new Date(), metodoPago = '') {
  const qty = carrito.find(i => i.id === producto.id)?.quantity || 1;
  return promotions.filter(p => promotionMatches(p, producto, fecha, metodoPago)).map(p => ({ ...p, calculation: calculatePromotionLine(p, producto, qty) }))
    .filter(p => p.calculation.discount > 0 && (p.autorizadaBajoCosto || p.calculation.unit >= producto.precioMinimo))
    .sort((a,b) => finiteNonNegative(b.prioridad) - finiteNonNegative(a.prioridad) || b.calculation.discount - a.calculation.discount);
}
function bestPromotion(product, quantity, method) { return obtenerPromocionesAplicables(product, [{ id: product.id, quantity }], new Date(), method)[0] || null; }

function statusBadge(state) { return `<span class="commercial-badge ${state.tone}">${escapeHtml(state.label)}</span>`; }
function pct(value) { return `${number(value).toFixed(2)}%`; }
function pricingProductRows(list = products) { return list.map(p => { const state = evaluarRentabilidadProducto(p); return `<tr><td><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.brand)} · ${escapeHtml(presentation(p))}</small></td><td>${escapeHtml(p.brand)}</td><td>${escapeHtml(presentation(p))}</td><td class="num">${money(p.costoPromedio)}</td><td class="num">${money(p.ultimoCostoCompra)}</td><td class="num">${money(p.precioVenta)}</td><td class="num">${money(calcularGananciaUnidad(p.precioVenta,p.costoPromedio))}</td><td class="num">${pct(calcularRecargoSobreCosto(p.precioVenta,p.costoPromedio))}</td><td class="num">${pct(calcularMargenSobreVenta(p.precioVenta,p.costoPromedio))}</td><td class="num">${money(p.precioMinimo)}</td><td>${statusBadge(state)}</td><td><button class="link-button" data-price-edit="${p.id}">Editar</button></td></tr>`; }).join(''); }
function summaryView() {
  const states = products.map(evaluarRentabilidadProducto), active = promotions.filter(p => promotionState(p)==='activa').length;
  const ending = promotions.filter(p => { const d=daysUntil(p.fechaFin); return d!==null&&d>=0&&d<=7; }).length;
  const expiring = products.filter(p => ['urgent','soon'].includes(expirationState(p)) && !obtenerPromocionesAplicables(p,[],new Date(),'').length).length;
  return `<div class="commercial-metrics">${[['Pérdida',states.filter(s=>s.key==='loss').length,'danger'],['Margen bajo',states.filter(s=>s.key==='low-margin').length,'warning'],['Por revisar',products.filter(p=>p.requiereRevisionPrecio).length,'info'],['Sin costo',states.filter(s=>s.key==='no-cost').length,'neutral'],['Sin precio',states.filter(s=>s.key==='no-price').length,'neutral'],['Promociones activas',active,'success'],['Finalizan pronto',ending,'warning'],['Vencen sin promo',expiring,'danger']].map(([l,v,t])=>`<article class="commercial-stat ${t}"><span>${l}</span><strong>${v}</strong></article>`).join('')}</div><div class="table-card"><div class="table-toolbar commercial-filters"><input id="priceSearch" type="search" placeholder="Nombre, marca o categoría…"><select id="priceState"><option value="all">Todos los estados</option><option value="loss">Venta con pérdida</option><option value="low-margin">Margen bajo</option><option value="review">Pendiente</option><option value="no-cost">Sin costo</option><option value="no-price">Sin precio</option><option value="profitable">Rentable</option></select></div><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Marca</th><th>Presentación</th><th>Costo prom.</th><th>Último costo</th><th>Precio</th><th>Ganancia</th><th>Recargo</th><th>Margen</th><th>Mínimo</th><th>Estado</th><th></th></tr></thead><tbody id="pricingProducts">${pricingProductRows()}</tbody></table></div></div>`;
}
function reviewView() { const list=products.filter(p=>p.requiereRevisionPrecio||['loss','low-margin','no-price'].includes(evaluarRentabilidadProducto(p).key)); return `<div class="section-head"><div><p class="eyebrow">BANDEJA</p><h2>Precios por revisar</h2></div><button class="primary-button compact" data-review-selected>APLICAR SUGERENCIAS</button></div><div class="table-card"><div class="table-wrap"><table><thead><tr><th></th><th>Producto</th><th>Stock</th><th>Último costo</th><th>Costo promedio</th><th>Precio actual</th><th>Mínimo</th><th>Sugerido</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${list.map(p=>{const suggested=redondearPrecioComercial(calcularPrecioSugerido(p.costoPromedio,p.porcentajeRecargoPredeterminado,'recargo'),p.tipoRedondeoPredeterminado);return `<tr><td><input type="checkbox" data-review-check="${p.id}"></td><td><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(presentation(p))}</small></td><td>${p.stock}</td><td>${money(p.ultimoCostoCompra)}</td><td>${money(p.costoPromedio)}</td><td>${money(p.precioVenta)}</td><td>${money(p.precioMinimo)}</td><td><strong>${money(suggested)}</strong></td><td>${statusBadge(evaluarRentabilidadProducto(p))}</td><td><button class="link-button" data-apply-suggested="${p.id}">Aplicar</button><button class="link-button" data-price-edit="${p.id}">Manual</button><button class="link-button" data-reviewed="${p.id}">Revisado</button></td></tr>`}).join('')||'<tr><td colspan="10">No hay precios pendientes. Todo está al día.</td></tr>'}</tbody></table></div></div>`; }
function bulkView() { return `<div class="panel"><div class="section-head"><div><p class="eyebrow">SIMULADOR SEGURO</p><h2>Actualización masiva</h2></div></div><div class="commercial-form-grid"><label>Alcance<select id="commercialBulkScope"><option value="all">Todos los productos</option><option value="category">Categoría</option><option value="brand">Marca</option><option value="low">Margen bajo</option><option value="review">Pendientes de revisión</option></select></label><label>Valor del alcance<input id="commercialBulkFilter" placeholder="Categoría o marca"></label><label>Operación<select id="commercialBulkOperation"><option value="increase">Aumentar por porcentaje</option><option value="decrease">Disminuir por porcentaje</option><option value="markup">Aplicar recargo objetivo</option><option value="margin">Aplicar margen objetivo</option><option value="fixed">Importe fijo adicional</option></select></label><label>Valor<input id="commercialBulkValue" type="number" min="0" step="0.01"></label><label>Redondeo<select id="commercialBulkRounding"><option value="none">Sin redondeo</option><option value="10">Múltiplo de 10</option><option value="50">Múltiplo de 50</option><option value="100">Múltiplo de 100</option><option value="up-10">Siempre hacia arriba</option></select></label></div><button class="secondary-button" data-bulk-preview>GENERAR VISTA PREVIA</button></div><div id="commercialBulkPreview" class="table-card commercial-preview"><div class="empty-state"><strong>Ningún cambio preparado</strong><small>Los precios sólo se modificarán después de revisar y confirmar.</small></div></div>`; }
function historyView() { return `<div class="table-card"><div class="table-toolbar commercial-filters"><input id="historySearch" type="search" placeholder="Producto o marca…"><select id="historyOrigin"><option value="all">Todos los orígenes</option>${[...new Set(priceHistory.map(h=>h.origen))].map(x=>`<option>${escapeHtml(x)}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Anterior</th><th>Nuevo</th><th>Diferencia</th><th>Margen</th><th>Motivo</th><th>Origen</th><th>Usuario</th></tr></thead><tbody id="priceHistoryRows">${historyRows(priceHistory)}</tbody></table></div></div>`; }
function historyRows(list) { return list.map(h=>`<tr><td>${escapeHtml(h.fecha)}<small>${escapeHtml(h.hora)}</small></td><td><strong>${escapeHtml(h.nombreProducto)}</strong><small>${escapeHtml(h.marca)} · ${escapeHtml(h.presentacion)}</small></td><td>${money(h.precioAnterior)}</td><td><strong>${money(h.precioNuevo)}</strong></td><td class="${h.diferenciaPesos<0?'negative':''}">${h.diferenciaPesos>0?'+':''}${money(h.diferenciaPesos)}<small>${pct(h.diferenciaPorcentaje)}</small></td><td>${pct(h.margenAnterior)} → ${pct(h.margenNuevo)}</td><td>${escapeHtml(h.motivo)}</td><td><span class="badge">${escapeHtml(h.origen)}</span></td><td>${escapeHtml(h.usuario)}</td></tr>`).join('')||'<tr><td colspan="9">Todavía no hay cambios de precios.</td></tr>'; }
function promotionsView() { return `<div class="section-head"><div><p class="eyebrow">REGLAS DEL POS</p><h2>Promociones activas y programadas</h2></div><button class="primary-button compact" data-promotion-new>＋ NUEVA PROMOCIÓN</button></div><div class="table-card"><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Tipo</th><th>Alcance</th><th>Vigencia</th><th>Estado</th><th>Prioridad</th><th>Acumulable</th><th>Aplicadas</th><th>Acciones</th></tr></thead><tbody>${promotions.map(p=>`<tr><td><strong>${escapeHtml(p.nombre)}</strong><small>${escapeHtml(p.descripcion||'')}</small></td><td>${escapeHtml(p.tipo.replaceAll('_',' '))}</td><td>${escapeHtml(p.alcance||'general')}</td><td>${formatDate(p.fechaInicio)} — ${formatDate(p.fechaFin)}</td><td>${statusBadge({label:promotionState(p),tone:promotionState(p)==='activa'?'success':'neutral'})}</td><td>${p.prioridad}</td><td>${p.acumulable?'Sí':'No'}</td><td>${p.unidadesAplicadas||0}</td><td><button class="link-button" data-promotion-edit="${p.id}">Editar</button><button class="link-button" data-promotion-toggle="${p.id}">${p.activa?'Pausar':'Activar'}</button><button class="link-button danger-text" data-promotion-delete="${p.id}">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="9">No hay promociones. Creá la primera para verla automáticamente en el POS.</td></tr>'}</tbody></table></div></div><div class="panel suggestion-panel"><h2>Sugerencias</h2>${promotionSuggestions()}</div>`; }
function promotionSuggestions(){const candidates=products.filter(p=>['urgent','soon'].includes(expirationState(p))||p.stock>(p.stockMinimo||p.minStock)*commercialSettings.highStockMultiplier).slice(0,5);return candidates.map(p=>`<div class="suggestion-row"><div><strong>${escapeHtml(p.name)}</strong><small>${['urgent','soon'].includes(expirationState(p))?'Está próximo a vencer':`Tiene ${p.stock} unidades en stock`}. Se sugiere evaluar un descuento del 10 %.</small></div><button class="link-button" data-suggest-promo="${p.id}">Crear promoción</button></div>`).join('')||'<div class="empty-state compact"><small>No hay sugerencias en este momento.</small></div>';}
function combosView(){return `<div class="section-head"><div><p class="eyebrow">VENTA CONJUNTA</p><h2>Combos</h2></div><button class="primary-button compact" data-combo-new>＋ NUEVO COMBO</button></div><div class="commercial-card-grid">${combos.map(c=>{const stock=Math.min(...(c.productos||[]).map(i=>Math.floor((products.find(p=>p.id===i.productoId)?.stock||0)/Math.max(1,i.cantidad))),0);return `<article class="panel combo-card"><span class="commercial-badge ${c.activo?'success':'neutral'}">${c.activo?'Activo':'Pausado'}</span><h3>${escapeHtml(c.nombre)}</h3><p>${escapeHtml(c.descripcion||'')}</p><ul>${(c.productos||[]).map(i=>`<li>${i.cantidad} × ${escapeHtml(products.find(p=>p.id===i.productoId)?.name||'Producto eliminado')}</li>`).join('')}</ul><div><span>Normal <s>${money(c.precioNormalTotal)}</s></span><strong>${money(c.precioCombo)}</strong></div><small>Stock disponible: ${stock}</small><button class="secondary-button" data-combo-toggle="${c.id}">${c.activo?'Pausar':'Activar'}</button></article>`}).join('')||'<div class="panel empty-state"><strong>No hay combos</strong><small>El stock se calculará siempre desde sus componentes reales.</small></div>'}</div>`;}
function settingsView(){return `<form id="commercialSettingsForm" class="panel"><div class="section-head"><div><p class="eyebrow">POLÍTICA COMERCIAL</p><h2>Configuración de márgenes</h2></div></div><div class="commercial-form-grid"><label>Recargo general (%)<input name="generalMarkup" type="number" min="0" step="0.01" value="${commercialSettings.generalMarkup}"></label><label>Margen mínimo (%)<input name="minimumMargin" type="number" min="0" max="99.99" step="0.01" value="${commercialSettings.minimumMargin}"></label><label>Margen objetivo (%)<input name="targetMargin" type="number" min="0" max="99.99" step="0.01" value="${commercialSettings.targetMargin}"></label><label>Redondeo general<select name="rounding"><option value="none">Sin redondeo</option><option value="10">Múltiplo de 10</option><option value="50">Múltiplo de 50</option><option value="100">Múltiplo de 100</option><option value="up-10">Siempre arriba</option></select></label><label>Descuento sin clave (%)<input name="discountLimit" type="number" min="0" max="100" value="${commercialSettings.discountLimit}"></label><label>Prioridad predeterminada<input name="defaultPriority" type="number" min="0" value="${commercialSettings.defaultPriority}"></label><label>Máximo masivo sin clave<input name="maxBulkWithoutAuth" type="number" min="1" value="${commercialSettings.maxBulkWithoutAuth}"></label><label class="checkbox-label"><input name="allowStacking" type="checkbox" ${commercialSettings.allowStacking?'checked':''}> Permitir acumulación</label></div><p class="form-note">Los valores específicos guardados por producto, categoría o marca tienen prioridad y no son reemplazados.</p><button class="primary-button compact">GUARDAR CONFIGURACIÓN</button></form>`;}
function renderPricing(){const content=$('#pricingContent');if(!content)return;const views={summary:summaryView,review:reviewView,bulk:bulkView,history:historyView,promotions:promotionsView,combos:combosView,'margin-settings':settingsView};content.innerHTML=views[pricingTab]();$$('[data-pricing-tab]').forEach(b=>b.classList.toggle('active',b.dataset.pricingTab===pricingTab));if(pricingTab==='margin-settings') $('#commercialSettingsForm [name="rounding"]').value=commercialSettings.rounding;}

function openPriceEditor(product){commercialAction={type:'price',id:product.id};$('#commercialTitle').textContent=`Editar precio · ${product.name}`;$('#commercialBody').innerHTML=`<div class="price-context"><span>Costo promedio <b>${money(product.costoPromedio)}</b></span><span>Último costo <b>${money(product.ultimoCostoCompra)}</b></span><span>Precio actual <b>${money(product.precioVenta)}</b></span><span>Precio mínimo <b>${money(product.precioMinimo)}</b></span><span>Margen actual <b>${pct(calcularMargenSobreVenta(product.precioVenta,product.costoPromedio))}</b></span></div><div class="commercial-form-grid"><label>Nuevo precio manual<input id="editPriceManual" type="number" min="0.01" step="0.01"></label><label>Porcentaje<input id="editPricePercent" type="number" min="0" step="0.01" value="${product.porcentajeRecargoPredeterminado}"></label><label>Tipo<select id="editPriceType"><option value="recargo">Recargo sobre costo</option><option value="margen">Margen sobre venta</option></select></label><label>Redondeo<select id="editPriceRounding"><option value="none">Sin redondeo</option><option value="10">Múltiplo de 10</option><option value="50">Múltiplo de 50</option><option value="100">Múltiplo de 100</option><option value="up-10">Siempre hacia arriba</option></select></label></div><div class="quick-recommendations">${[20,25,30,35,40,50].map(x=>`<button type="button" data-edit-percent="${x}">${x}%</button>`).join('')}</div><div id="editPricePreview" class="purchase-preview"></div>`;$('#editPriceRounding').value=product.tipoRedondeoPredeterminado;$('#commercialDialog').showModal();renderPricePreview();}
function renderPricePreview(){if(commercialAction?.type!=='price')return;const p=products.find(x=>x.id===commercialAction.id),manual=finiteNonNegative($('#editPriceManual').value),raw=manual||calcularPrecioSugerido(p.costoPromedio,$('#editPricePercent').value,$('#editPriceType').value),rounded=manual||redondearPrecioComercial(raw,$('#editPriceRounding').value),state=evaluarRentabilidadProducto(p,rounded);$('#editPricePreview').innerHTML=`<div class="recommend-summary"><div><span>Sin redondear</span><strong>${money(raw)}</strong></div><div><span>Precio final</span><strong>${money(rounded)}</strong></div><div><span>Ganancia</span><strong>${money(calcularGananciaUnidad(rounded,p.costoPromedio))}</strong></div><div><span>Recargo</span><strong>${pct(calcularRecargoSobreCosto(rounded,p.costoPromedio))}</strong></div><div><span>Margen</span><strong>${pct(calcularMargenSobreVenta(rounded,p.costoPromedio))}</strong></div><div><span>Estado</span><strong>${state.label}</strong></div></div>${rounded<p.precioMinimo?'<p class="profit-warning danger">El resultado queda por debajo del precio mínimo.</p>':''}`;}
function openPromotionEditor(promo={},productId=''){commercialAction={type:'promotion',id:promo.id||''};$('#commercialTitle').textContent=promo.id?'Editar promoción':'Nueva promoción';const selected=promo.productoIds?.[0]||productId;$('#commercialBody').innerHTML=`<div class="commercial-form-grid"><label>Nombre<input id="promoName" required value="${escapeHtml(promo.nombre||'')}"></label><label>Tipo<select id="promoType">${[['porcentaje','Descuento porcentual'],['fijo','Descuento fijo'],['precio_fijo','Precio promocional'],['cantidad','Cantidad por precio'],['dos_por_uno','2x1'],['tres_por_dos','3x2'],['segunda_descuento','Segunda unidad con descuento'],['desde_cantidad','Desde cierta cantidad'],['categoria','Por categoría'],['marca','Por marca'],['metodo_pago','Por método de pago']].map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Producto<select id="promoProduct"><option value="">Todos</option>${products.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${escapeHtml(p.name)} · ${escapeHtml(p.brand)}</option>`).join('')}</select></label><label>Categoría<input id="promoCategory" value="${escapeHtml(promo.categoriaIds?.[0]||'')}"></label><label>Marca<input id="promoBrand" value="${escapeHtml(promo.marcaIds?.[0]||'')}"></label><label>Porcentaje<input id="promoPercent" type="number" min="0" max="100" value="${promo.porcentaje||0}"></label><label>Descuento fijo<input id="promoFixed" type="number" min="0" value="${promo.descuentoFijo||0}"></label><label>Precio promocional / cantidad<input id="promoPrice" type="number" min="0" value="${promo.precioPromocional||0}"></label><label>Cantidad requerida<input id="promoRequired" type="number" min="0" value="${promo.cantidadRequerida||0}"></label><label>Inicio<input id="promoStart" type="date" value="${promo.fechaInicio||new Date().toISOString().slice(0,10)}"></label><label>Fin<input id="promoEnd" type="date" value="${promo.fechaFin||''}"></label><label>Hora inicio<input id="promoTimeStart" type="time" value="${promo.horaInicio||''}"></label><label>Hora fin<input id="promoTimeEnd" type="time" value="${promo.horaFin||''}"></label><label>Prioridad<input id="promoPriority" type="number" min="0" value="${promo.prioridad??commercialSettings.defaultPriority}"></label><label>Método de pago<select id="promoPayment"><option value="">Todos</option>${['Efectivo','Tarjeta de débito','Tarjeta de crédito','QR','Transferencia'].map(x=>`<option ${promo.metodoPagoIds?.includes(x)?'selected':''}>${x}</option>`).join('')}</select></label><label class="checkbox-label"><input id="promoStack" type="checkbox" ${promo.acumulable?'checked':''}> Acumulable</label></div><p class="form-note">La rentabilidad se valida antes de activar. El precio normal nunca se modifica.</p>`;$('#promoType').value=promo.tipo||'porcentaje';$('#commercialDialog').showModal();}
function submitCommercial(event){event.preventDefault();if(commercialAction?.type==='price'){const p=products.find(x=>x.id===commercialAction.id),manual=finiteNonNegative($('#editPriceManual').value),raw=manual||calcularPrecioSugerido(p.costoPromedio,$('#editPricePercent').value,$('#editPriceType').value);if($('#editPriceType').value==='margen'&&finiteNonNegative($('#editPricePercent').value)>=100)return showToast('El margen debe ser menor que 100 %','error');const next=manual||redondearPrecioComercial(raw,$('#editPriceRounding').value);if(next<p.precioMinimo&&!authorizeSensitive('El precio queda por debajo del mínimo.'))return;updateProductPrice(p,next,'Edición individual confirmada','edición manual');}
  if(commercialAction?.type==='promotion'){const existing=promotions.find(p=>p.id===commercialAction.id)||{},now=new Date().toISOString(),promo={...existing,id:existing.id||`promo-${uid()}`,nombre:$('#promoName').value.trim(),descripcion:existing.descripcion||'',tipo:$('#promoType').value,alcance:$('#promoProduct').value?'productos':$('#promoCategory').value?'categorias':$('#promoBrand').value?'marcas':'general',productoIds:$('#promoProduct').value?[$('#promoProduct').value]:[],categoriaIds:$('#promoCategory').value?[$('#promoCategory').value.trim()]:[],marcaIds:$('#promoBrand').value?[$('#promoBrand').value.trim()]:[],fechaInicio:$('#promoStart').value,fechaFin:$('#promoEnd').value,horaInicio:$('#promoTimeStart').value,horaFin:$('#promoTimeEnd').value,diasSemana:existing.diasSemana||[],porcentaje:finiteNonNegative($('#promoPercent').value),descuentoFijo:finiteNonNegative($('#promoFixed').value),precioPromocional:finiteNonNegative($('#promoPrice').value),cantidadRequerida:finiteNonNegative($('#promoRequired').value),cantidadCobrada:existing.cantidadCobrada||0,prioridad:finiteNonNegative($('#promoPriority').value),acumulable:$('#promoStack').checked,activa:true,estado:'activa',limiteUnidades:existing.limiteUnidades??null,unidadesAplicadas:existing.unidadesAplicadas||0,metodoPagoIds:$('#promoPayment').value?[$('#promoPayment').value]:[],fechaCreacion:existing.fechaCreacion||now,fechaModificacion:now};if(!promo.nombre)return showToast('Ingresá un nombre','error');const affected=products.filter(p=>promotionMatches({...promo,fechaInicio:'',fechaFin:'',horaInicio:'',horaFin:'',estado:'activa'},p,new Date(),promo.metodoPagoIds[0]||''));const below=affected.filter(p=>calculatePromotionLine(promo,p,Math.max(1,promo.cantidadRequerida||1)).unit<p.costoPromedio);if(below.length&&!authorizeSensitive(`La promoción vende ${below.length} producto(s) por debajo del costo.`))return;promo.autorizadaBajoCosto=below.length>0;if(existing.id)Object.assign(existing,promo);else promotions.unshift(promo);}
  persistCommercial();$('#commercialDialog').close();renderAll();renderPricing();showToast('Cambios comerciales guardados');commercialAction=null;}

const legacySaleTotals = saleTotals;
saleTotals = function promotionalSaleTotals(){const base=legacySaleTotals(),method=$('#paymentMethod').value;let normalSubtotal=0,promotionalSubtotal=0;cart.forEach(i=>{const p=products.find(x=>x.id===i.id),promo=bestPromotion(p,i.quantity,method),calc=promo?.calculation||{normal:i.price*i.quantity,total:i.price*i.quantity,discount:0,unit:i.price};i.promotion=promo?{id:promo.id,name:promo.nombre}:null;i.promotionalUnitPrice=calc.unit;i.promotionalDiscount=calc.discount;normalSubtotal+=calc.normal;promotionalSubtotal+=calc.total;});const signed=base.type==='discount'?-1:base.type==='surcharge'?1:0,amount=promotionalSubtotal*base.percent/100*signed;return {...base,normalSubtotal,promotionDiscount:normalSubtotal-promotionalSubtotal,subtotal:promotionalSubtotal,amount,total:Math.max(0,promotionalSubtotal+amount+base.shippingAmount)};};
const legacyRenderCart=renderCart;
renderCart=function renderPromotionalCart(){legacyRenderCart();const t=saleTotals();$('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><div><h3>${escapeHtml(i.name)}</h3><small>${escapeHtml(i.brand)} · ${escapeHtml(i.presentation)}</small>${i.promotion?`<span class="promotion-line"><s>${money(i.price)} c/u</s> <b>${money(i.promotionalUnitPrice)} c/u</b> · ${escapeHtml(i.promotion.name)}</span>`:`<small>${money(i.price)} c/u</small>`}<div class="quantity"><button data-minus="${i.id}">−</button><strong>${i.quantity}</strong><button data-plus="${i.id}">＋</button><button data-remove="${i.id}">×</button></div></div><strong class="num">${money(i.promotionalUnitPrice*i.quantity)}</strong></div>`).join(''):'<div class="empty-state"><span>◇</span><strong>Tu venta está vacía</strong><small>Tocá un producto para agregarlo.</small></div>';$('#subtotal').textContent=money(t.normalSubtotal);let row=$('#promotionTotalRow');if(!row){row=document.createElement('div');row.id='promotionTotalRow';$('#adjustmentRow').before(row);}row.innerHTML=`<span>Descuentos promocionales</span><strong class="num">-${money(t.promotionDiscount)}</strong>`;row.hidden=!t.promotionDiscount;$('#adjustmentAmount').textContent=`${t.amount>0?'+':''}${money(t.amount)}`;$('#total').textContent=money(t.total);};

const previousSave=save;save=function saveWithCommercial(){previousSave();guardarPromociones();guardarCombos();guardarHistorialPrecios();guardarConfiguracionComercial();};
const previousRenderAll=renderAll;renderAll=function renderWithPricing(){previousRenderAll();renderPricing();};

$('#commercialForm').addEventListener('submit',submitCommercial);
$('#commercialBody').addEventListener('input',e=>{if(e.target.matches('#editPriceManual,#editPricePercent,#editPriceType,#editPriceRounding'))renderPricePreview();});
document.addEventListener('click',e=>{const tab=e.target.closest('[data-pricing-tab]');if(tab){pricingTab=tab.dataset.pricingTab;renderPricing();}const edit=e.target.closest('[data-price-edit]');if(edit)openPriceEditor(products.find(p=>p.id===edit.dataset.priceEdit));const quick=e.target.closest('[data-edit-percent]');if(quick){$('#editPricePercent').value=quick.dataset.editPercent;$('#editPriceManual').value='';renderPricePreview();}const apply=e.target.closest('[data-apply-suggested]');if(apply){const p=products.find(x=>x.id===apply.dataset.applySuggested),next=redondearPrecioComercial(calcularPrecioSugerido(p.costoPromedio,p.porcentajeRecargoPredeterminado,'recargo'),p.tipoRedondeoPredeterminado);updateProductPrice(p,next,'Precio sugerido confirmado','edición manual');persistCommercial();renderAll();}const reviewed=e.target.closest('[data-reviewed]');if(reviewed){products.find(p=>p.id===reviewed.dataset.reviewed).requiereRevisionPrecio=false;persistCommercial();renderAll();}if(e.target.closest('[data-promotion-new]'))openPromotionEditor();const pe=e.target.closest('[data-promotion-edit]');if(pe)openPromotionEditor(promotions.find(p=>p.id===pe.dataset.promotionEdit));const ps=e.target.closest('[data-suggest-promo]');if(ps)openPromotionEditor({},ps.dataset.suggestPromo);const pt=e.target.closest('[data-promotion-toggle]');if(pt){const p=promotions.find(x=>x.id===pt.dataset.promotionToggle);p.activa=!p.activa;p.estado=p.activa?'activa':'pausada';persistCommercial();renderPricing();}const pd=e.target.closest('[data-promotion-delete]');if(pd&&authorizeSensitive('Eliminar promociones requiere autorización.')){promotions=promotions.filter(p=>p.id!==pd.dataset.promotionDelete);persistCommercial();renderPricing();}if(e.target.closest('[data-bulk-preview]'))prepareBulkPreview();const ca=e.target.closest('[data-confirm-bulk]');if(ca)confirmCommercialBulk();const ct=e.target.closest('[data-combo-toggle]');if(ct){const c=combos.find(x=>x.id===ct.dataset.comboToggle);c.activo=!c.activo;persistCommercial();renderPricing();}if(e.target.closest('[data-combo-new]'))createSimpleCombo();});
$('#pricingContent').addEventListener('input',e=>{if(e.target.id==='priceSearch'||e.target.id==='priceState'){const q=($('#priceSearch')?.value||'').toLowerCase(),state=$('#priceState')?.value||'all';$('#pricingProducts').innerHTML=pricingProductRows(products.filter(p=>(`${p.name} ${p.brand} ${p.category}`).toLowerCase().includes(q)&&(state==='all'||evaluarRentabilidadProducto(p).key===state)));}if(e.target.id==='historySearch'||e.target.id==='historyOrigin'){const q=($('#historySearch')?.value||'').toLowerCase(),origin=$('#historyOrigin')?.value||'all';$('#priceHistoryRows').innerHTML=historyRows(priceHistory.filter(h=>(`${h.nombreProducto} ${h.marca}`).toLowerCase().includes(q)&&(origin==='all'||h.origen===origin)));}});
$('#pricingContent').addEventListener('submit',e=>{if(e.target.id!=='commercialSettingsForm')return;e.preventDefault();if(!authorizeSensitive('Cambiar la política comercial requiere autorización.'))return;const data=new FormData(e.target);commercialSettings={...commercialSettings,generalMarkup:finiteNonNegative(data.get('generalMarkup')),minimumMargin:Math.min(99.99,finiteNonNegative(data.get('minimumMargin'))),targetMargin:Math.min(99.99,finiteNonNegative(data.get('targetMargin'))),rounding:data.get('rounding'),discountLimit:finiteNonNegative(data.get('discountLimit')),defaultPriority:finiteNonNegative(data.get('defaultPriority')),maxBulkWithoutAuth:Math.max(1,finiteNonNegative(data.get('maxBulkWithoutAuth'))),allowStacking:data.get('allowStacking')==='on'};persistCommercial();renderPricing();showToast('Configuración comercial guardada');});
function prepareBulkPreview(){const scope=$('#commercialBulkScope').value,filter=$('#commercialBulkFilter').value.trim().toLowerCase(),operation=$('#commercialBulkOperation').value,value=finiteNonNegative($('#commercialBulkValue').value),rounding=$('#commercialBulkRounding').value;if(!value)return showToast('Ingresá un valor válido','error');let list=products.filter(p=>scope==='all'||scope==='category'&&p.category.toLowerCase()===filter||scope==='brand'&&p.brand.toLowerCase()===filter||scope==='low'&&evaluarRentabilidadProducto(p).key==='low-margin'||scope==='review'&&p.requiereRevisionPrecio);bulkPricePreview=list.map(p=>{let next=p.precioVenta;if(operation==='increase')next*=1+value/100;if(operation==='decrease')next*=1-value/100;if(operation==='markup')next=calcularPrecioSugerido(p.costoPromedio,value,'recargo');if(operation==='margin')next=calcularPrecioSugerido(p.costoPromedio,value,'margen');if(operation==='fixed')next+=value;next=redondearPrecioComercial(next,rounding);return{p,next,warning:next<p.precioMinimo?'Debajo del mínimo':''};});$('#commercialBulkPreview').innerHTML=`<div class="table-wrap"><table><thead><tr><th></th><th>Producto</th><th>Actual</th><th>Costo</th><th>Nuevo</th><th>Diferencia</th><th>Margen</th><th>Advertencia</th></tr></thead><tbody>${bulkPricePreview.map((x,i)=>`<tr><td><input type="checkbox" data-bulk-check="${i}" checked></td><td>${escapeHtml(x.p.name)}</td><td>${money(x.p.precioVenta)}</td><td>${money(x.p.costoPromedio)}</td><td><strong>${money(x.next)}</strong></td><td>${money(x.next-x.p.precioVenta)}</td><td>${pct(calcularMargenSobreVenta(x.next,x.p.costoPromedio))}</td><td class="negative">${x.warning}</td></tr>`).join('')}</tbody></table></div><button class="primary-button compact bulk-confirm" data-confirm-bulk>CONFIRMAR ${bulkPricePreview.length} CAMBIOS</button>`;}
function confirmCommercialBulk(){const selected=[...$$('[data-bulk-check]:checked')].map(c=>bulkPricePreview[Number(c.dataset.bulkCheck)]).filter(Boolean);if(!selected.length)return showToast('Seleccioná al menos un producto','error');const sensitive=selected.some(x=>x.next<x.p.precioVenta||x.next<x.p.precioMinimo)||selected.length>commercialSettings.maxBulkWithoutAuth;if(sensitive&&!authorizeSensitive(`La operación afecta ${selected.length} productos o reduce precios.`))return;if(!confirm(`Se actualizarán ${selected.length} productos. ¿Confirmar?`))return;selected.forEach(x=>updateProductPrice(x.p,x.next,'Actualización masiva confirmada','actualización masiva'));persistCommercial();bulkPricePreview=[];renderAll();showToast(`Se actualizaron ${selected.length} precios`);}
function createSimpleCombo(){if(products.length<2)return showToast('Necesitás al menos dos productos','error');const name=prompt('Nombre del combo:');if(!name)return;const ids=prompt(`IDs separados por coma:\n${products.map(p=>`${p.id}: ${p.name}`).join('\n')}`)?.split(',').map(x=>x.trim()).filter(id=>products.some(p=>p.id===id));if(!ids?.length)return showToast('No se seleccionaron productos válidos','error');const items=ids.map(productoId=>({productoId,cantidad:1})),normal=items.reduce((s,i)=>s+products.find(p=>p.id===i.productoId).precioVenta,0),price=finiteNonNegative(prompt('Precio del combo:',normal));if(!price)return;combos.unshift({id:`combo-${uid()}`,nombre:name,descripcion:'',productos:items,precioNormalTotal:normal,precioCombo:price,ahorro:normal-price,fechaInicio:new Date().toISOString().slice(0,10),fechaFin:'',diasSemana:[],horaInicio:'',horaFin:'',activo:true,prioridad:commercialSettings.defaultPriority,acumulable:false});persistCommercial();renderPricing();}

migrateCommercialProducts();
// Compras ya registradas sin aceptar sugerencia entran de forma automática en revisión.
products.forEach(p=>{const state=evaluarRentabilidadProducto(p);if(['loss','low-margin','no-price'].includes(state.key))p.requiereRevisionPrecio=true;});
persistCommercial();renderAll();

function registrarUsoPromociones(items) {
  items.forEach(item => {
    if (!item.promocionId) return;
    const promotion = promotions.find(p => p.id === item.promocionId);
    if (promotion) promotion.unidadesAplicadas = finiteNonNegative(promotion.unidadesAplicadas) + item.cantidad;
  });
  guardarPromociones();
}
